name: Project2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.2

  animated_text_kit: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
#  table_calendar: ^3.0.0
#  table_calendar: ^3.0.8
  table_calendar: ^3.0.7
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  lottie: ^1.2.1
  fl_chart: ^0.60.0


flutter:
  uses-material-design: true

